### ISSUE TITLE
How can i use this appllication without updating to Windows 7 or making a virtual machine for Windows 7? (VISTA USER)

### ISSUE THREAD

**Issue by PF94** [erfg12/AOL_4.0_Emu#23]
I found out about this software due to a 2-year-long bump, However, it requires .NET 4.6.1, however, the last version for vista is 4.6, this means i'm one revision off from using this app.

Although, the solution for most people is "Dude, go update to Windows 7/8.1/10", i don't really want to update to those OSes are they're overrated.

I am not sure on what's the difference between 4.6 and 4.6.1, likely just a rebranded 4.6 to make some apps uncompatible with Vista.

**Comment by erfg12** [comment]
AOL 4.0 Emu uses several other 3rd party libraries. Some of these third party libraries require higher level .NET frameworks due to certain functions they're using. However, it does look like I can lower it to 4.6.0, but I have no idea how long that will be good for as at any time the 3rd party libraries could raise their framework version.

A nightly build should be ready soon, as I just pushed the changes to the repo.

**Comment by PF94** [comment]
thanks
